### ISSUE TITLE
基础设施~文件管理~上传文件bug？

### ISSUE THREAD

**Issue by justin-wick** [YunaiV/ruoyi-vue-pro#111]
前端VUE请求地址为：http://localhost/dev-api/api//infra/file/upload
后端MultiUserDetailsAuthenticationProvider#getUserType 中request.getRequestURI()值为：/api/infra/file/upload
导致抛出异常：
java.lang.IllegalArgumentException: URI(/api/infra/file/upload) 找不到匹配的用户类型
 at cn.iocoder.yudao.framework.security.core.authentication.MultiUserDetailsAuthenticationProvider.getUserType(MultiUserDetailsAuthenticationProvider.java:146)
 at cn.iocoder.yudao.framework.security.core.authentication.MultiUserDetailsAuthenticationProvider.selectService(MultiUserDetailsAuthenticationProvider.java:131)
 at cn.iocoder.yudao.framework.security.core.authentication.MultiUserDetailsAuthenticationProvider.verifyTokenAndRefresh(MultiUserDetailsAuthenticationProvider.java:105)
 at cn.iocoder.yudao.framework.security.core.filter.JWTAuthenticationTokenFilter.doFilterInternal(JWTAuthenticationTokenFilter.java:43)
 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)

**请问这是一个bug，还是我哪里没配置对？**

**Comment by YunaiV** [comment]
正在 fix，这周会上传一个新版本的文件模块
