### ISSUE TITLE
7.3 启动 Vue2 管理后台 跑不起来

### ISSUE THREAD

**Issue by codezc** [YunaiV/ruoyi-vue-pro#263]
D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin>yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @vue/cli-plugin-eslint@4.5.18" has incorrect peer dependency "eslint@>= 1.6.0 < 7.0.0".
warning "@vue/cli-plugin-eslint > eslint-loader@2.2.1" has incorrect peer dependency "eslint@>=1.6.0 <7.0.0".
warning " > @vue/eslint-config-prettier@5.1.0" has unmet peer dependency "prettier@>= 1.13.0".
warning " > compression-webpack-plugin@5.0.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > eslint-plugin-prettier@3.4.1" has unmet peer dependency "prettier@>=1.13.0".
warning " > sass-loader@10.2.0" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
warning " > script-ext-html-webpack-plugin@2.1.5" has unmet peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0 || ^4.0.0".
warning " > script-ext-html-webpack-plugin@2.1.5" has unmet peer dependency "html-webpack-plugin@^3.0.0 || ^4.0.0".
warning " > terser-webpack-plugin@4.2.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 33.76s.

D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin>npm run local

> yudao-ui-admin@1.7.1-snapshot local
> vue-cli-service serve --mode local

Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
 INFO  Starting development server...
10% building 2/5 modules 3 active ...7.2\yudao-ui-admin\node_modules\eslint-loader\index.js??ref--14-0!D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\src\main.jsError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at D:\projects\qingerai\lightingweb\ruoyi-vue-pro-1.7.2\yudao-ui-admin\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1

**Comment by YunaiV** [comment]
换 14 或 16
