### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by coderYarn** [YunaiV/ruoyi-vue-pro#266]
node:14.16.0
npm:6.14.11

failed to load config from C:\Users\EDY\Desktop\xinqiao\swsjr-ui\yudao-ui-admin-vue3\vite.config.ts
error when starting dev server:
Error: Cannot find module 'node:path'
Require stack:
- C:\Users\EDY\Desktop\xinqiao\swsjr-ui\yudao-ui-admin-vue3\node_modules\vite\dist\node-cjs\publicUtils.cjs
- C:\Users\EDY\Desktop\xinqiao\swsjr-ui\yudao-ui-admin-vue3\node_modules\vite\index.cjs
- C:\Users\EDY\Desktop\xinqiao\swsjr-ui\yudao-ui-admin-vue3\vite.config.ts
- C:\Users\EDY\Desktop\xinqiao\swsjr-ui\yudao-ui-admin-vue3\node_modules\vite\dist\node\chunks\dep-24daf00c.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\EDY\Desktop\xinqiao\swsjr-ui\yudao-ui-admin-vue3\node_modules\vite\dist\node-cjs\publicUtils.cjs:3:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object._require.extensions.<computed> [as .js] (file:///C:/Users/EDY/Desktop/xinqiao/swsjr-ui/yudao-ui-admin-vue3/node_modules/vite/dist/node/chunks/dep-24daf00c.js:64459:17)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yudao-ui-admin-vue3@1.7.2-snapshot dev: `vite --mode base`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yudao-ui-admin-vue3@1.7.2-snapshot dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\EDY\AppData\Roaming\npm-cache\_logs\2023-05-08T01_05_59_605Z-debug.log

**Comment by YunaiV** [comment]
使用 node16 版本。
