### ISSUE TITLE
websocket连接导致devServer直接卡死

### ISSUE THREAD

**Issue by dlh996** [YunaiV/ruoyi-vue-pro#306]
### 基本信息

 此问题出现在vue2前端工程。

- ruoyi-vue-pro 版本：1.7.3-snapshot
- 操作系统：MacOS 12.6.7
- 数据库：5.7.42
- nodejs版本：14.21.3

### 你猜测可能的原因

未知

### 复现步骤

第一步，修改vue.config.js文件。为devserver添加websocket支持。
```
devServer: {
    host: "0.0.0.0",
    port: port,
    open: true,
    proxy: {
      ["/proxy-api"]: {
        target: `http://localhost:48080`,
        changeOrigin: true,
        ws: true,  //添加该配置
        pathRewrite: {
          ["^" + process.env.VUE_APP_BASE_API]: "",
        },
      },
    },
    disableHostCheck: true,
  },
```

第二步，启动前端服务与后端服务

第三步，通过前端端口1024 请求websocket。ws://localhost:1024/proxy-api/websocket/message?userId=1

### 报错信息
```
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on Socket instance at:
    at Socket.onerror (internal/streams/readable.js:750:14)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/22029832/c855882f-642c-429b-b244-c49fb70f1d7e)

带上必要的截图

**Comment by dlh996** [comment]
已解决，请大佬直接关闭了吧
