### ISSUE TITLE
postgresql 数据库定时任务报错  MisfireHandler: Error handling misfires: Couldn't retrieve trigger: invalid stream header: 5C323534

### ISSUE THREAD

**Issue by DavidSche** [YunaiV/ruoyi-vue-pro#441]
下载的yudao-boot-mini-v2.0.1 版本，创建完成数据库后，启动报错

2024-03-13 16:16:59.628 |  INFO 27825 | main [TID: N/A] o.s.s.quartz.LocalDataSourceJobStore     | ClusterManager: Scanning for instance "DESKTOP-MUCR7FM1710317634882"'s failed in-progress jobs.
2024-03-13 16:16:59.661 |  INFO 27825 | main [TID: N/A] org.quartz.core.QuartzScheduler          | Scheduler schedulerName_$_massdatas1710317812254 started.
2024-03-13 16:16:59.674 |  INFO 27825 | QuartzScheduler_schedulerName-massdatas1710317812254_MisfireHandler [TID: N/A] o.s.s.quartz.LocalDataSourceJobStore     | Handling 1 trigger(s) that missed their scheduled fire-time.
2024-03-13 16:16:59.687 | ERROR 27825 | QuartzScheduler_schedulerName-massdatas1710317812254_MisfireHandler [TID: N/A] o.s.s.quartz.LocalDataSourceJobStore     | MisfireHandler: Error handling misfires: Couldn't retrieve trigger: invalid stream header: 5C323534

org.quartz.JobPersistenceException: Couldn't retrieve trigger: invalid stream header: 5C323534
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveTrigger(JobStoreSupport.java:1538)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.recoverMisfiredJobs(JobStoreSupport.java:984)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3264)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:4012)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4033)
Caused by: java.io.StreamCorruptedException: invalid stream header: 5C323534
        at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:989)
        at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:416)
        at org.quartz.impl.jdbcjobstore.PostgreSQLDelegate.getObjectFromBlob(PostgreSQLDelegate.java:71)
        at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectTrigger(StdJDBCDelegate.java:1780)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveTrigger(JobStoreSupport.java:1536)
        ... 4 common frames omitted

**Comment by YunaiV** [comment]
“invalid stream header: 5C323534 pgsql”错误表示 PostgreSQL 服务器无法识别客户端发送的流标头。流标头是客户端和服务器在建立连接时交换的一系列字节，用于协商通信协议的版本和功能。

出现此错误的原因可能是：

* **客户端和服务器之间的协议不匹配：**确保你使用的 PostgreSQL 客户端和服务器版本兼容。
* **防火墙或网络问题：**检查客户端和服务器之间的网络连接是否正常，并且防火墙没有阻止通信。
* **客户端库错误：**更新或重新安装你使用的 PostgreSQL 客户端库。
* **服务器配置错误：**检查 PostgreSQL 服务器配置是否正确，特别是与流协议相关的设置。

要解决此问题，请尝试以下步骤：

1. 确保客户端和服务器使用相同的 PostgreSQL 主要版本（例如，9.6、10、11 等）。
2. 检查网络连接并确保防火墙允许客户端和服务器之间的通信。
3. 更新或重新安装客户端 PostgreSQL 库。
4. 检查服务器配置，特别是与流协议相关的设置，例如 `listen_addresses`、`port` 和 `ssl`。

如果仍然遇到问题，请查看 PostgreSQL 文档以获取更多故障排除信息，或在 PostgreSQL 论坛或社区上寻求帮助。
