### ISSUE TITLE
swagger 接口文档问题

### ISSUE THREAD

**Issue by zhangle910522** [YunaiV/ruoyi-vue-pro#639]
拉取Master代码之后  访问 http://localhost:48080/doc.html
发现所有的接口生成的文档都是  content-type:application/x-www-form-urlencoded  提交请求报 500错误  
org.springframework.web.HttpMediaTypeNotSupportedException: Content type 'application/x-www-form-urlencoded;charset=UTF-8' not supported
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:211)
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:160)
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:133)
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:122)
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:179)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:146)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)

<img width="832" alt="image" src="https://github.com/user-attachments/assets/8bf59769-a61e-4c8d-ae4f-1592364f2f80">

**Comment by zhangle910522** [comment]
为啥不是  json？

**Comment by zhangle910522** [comment]
<img width="711" alt="image" src="https://github.com/user-attachments/assets/fbaaa8c0-00f8-4631-a2e4-e44636ba49f5">
导入到 apifox 之后 Content-Type 也不是application/json

**Comment by sing173** [comment]
同样问题，希望尽快解决

**Comment by mircg** [comment]
![35086623a9594f096cc55e15e057e5c](https://github.com/user-attachments/assets/043c43d9-72f7-49b7-80b0-e54cb6a82728)
修改一下，就可以了

**Comment by YunaiV** [comment]
master-jdk17 解决了，这个是 knife4j 的 bug。。。

https://t.zsxq.com/Urhsr 星球也有人反馈类似问题。

https://doc.iocoder.cn/api-doc/ 这里我解释了下原因。。。

= = 很尴尬

**Comment by Mrgongm** [comment]
请问master 如何解决

**Comment by D2Moqi** [comment]
修改接口文档依赖 <springdoc.version>1.8.0</springdoc.version> 和 关闭 knife4j.enable 增强模式 后可以正常使用。参考：https://blog.csdn.net/qq_39609993/article/details/141873658

**Comment by YunaiV** [comment]
> 修改接口文档依赖 <springdoc.version>1.8.0</springdoc.version> 和 关闭 knife4j.enable 增强模式 后可以正常使用。参考：https://blog.csdn.net/qq_39609993/article/details/141873658

已参考修复，感谢
