### ISSUE TITLE
BUG 报告：TenantContextHolder 不存在租户编号，可能是多线程 bug

### ISSUE THREAD

**Issue by crimson-gao** [YunaiV/ruoyi-vue-pro#64]
运行过程中会每隔一段时间出现 ` java.lang.NullPointerException: TenantContextHolder 不存在租户编号` 这样的 bug，看了下代码，用户在每次请求时会触发 TenantContextWebFilter ，设置 tenant id。
但是 tenant id 使用 tenantContextHolder 保存在 threadLocal 内，在断点调试中显示 setTenant 的线程名是 http-nio-xxxxx。
然后程序中又有一类使用 @scheduled 注解的定时任务，这些定时任务也会去执行函数，继而调用 getRequiredTenantId，然后可能执行这个定时任务的线程没有 setTenant id 过，就报 nullPointerException 了。断点中该线程名为 Scheduler-1

```text
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: java.lang.NullPointerException: TenantContextHolder 不存在租户编号
### Cause: java.lang.NullPointerException: TenantContextHolder 不存在租户编号
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:96)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy136.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:166)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:77)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy162.selectList(Unknown Source)
	at com.baomidou.mybatisplus.core.mapper.BaseMapper.selectOne(BaseMapper.java:174)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$DefaultMethodInvoker.invoke(MybatisMapperProxy.java:162)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy162.selectOne(Unknown Source)
	at cn.iocoder.yudao.adminserver.modules.system.dal.mysql.dept.SysDeptMapper.selectExistsByUpdateTimeAfter(SysDeptMapper.java:34)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$DefaultMethodInvoker.invoke(MybatisMapperProxy.java:162)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy162.selectExistsByUpdateTimeAfter(Unknown Source)
	at cn.iocoder.yudao.adminserver.modules.system.service.dept.impl.SysDeptServiceImpl.loadDeptIfUpdate(SysDeptServiceImpl.java:116)
	at cn.iocoder.yudao.adminserver.modules.system.service.dept.impl.SysDeptServiceImpl.initLocalCache(SysDeptServiceImpl.java:79)
	at cn.iocoder.yudao.adminserver.modules.system.service.dept.impl.SysDeptServiceImpl.schedulePeriodicRefresh(SysDeptServiceImpl.java:101)
	at cn.iocoder.yudao.adminserver.modules.system.service.dept.impl.SysDeptServiceImpl$$FastClassBySpringCGLIB$$5f1de7b3.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:123)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at cn.iocoder.yudao.adminserver.modules.system.service.dept.impl.SysDeptServiceImpl$$EnhancerBySpringCGLIB$$fa651d8.schedulePeriodicRefresh(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: java.lang.NullPointerException: TenantContextHolder 不存在租户编号
### Cause: java.lang.NullPointerException: TenantContextHolder 不存在租户编号
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:153)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:145)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
	... 44 common frames omitted
Caused by: java.lang.NullPointerException: TenantContextHolder 不存在租户编号
	at cn.iocoder.yudao.framework.tenant.core.context.TenantContextHolder.getRequiredTenantId(TenantContextHolder.java:36)
	at cn.iocoder.yudao.framework.tenant.core.db.TenantDatabaseInterceptor.getTenantId(TenantDatabaseInterceptor.java:25)
	at com.baomidou.mybatisplus.extension.plugins.inner.TenantLineInnerInterceptor.builderExpression(TenantLineInnerInterceptor.java:446)
	at com.baomidou.mybatisplus.extension.plugins.inner.TenantLineInnerInterceptor.processPlainSelect(TenantLineInnerInterceptor.java:244)
	at com.baomidou.mybatisplus.extension.plugins.inner.TenantLineInnerInterceptor.processSelectBody(TenantLineInnerInterceptor.java:98)
	at com.baomidou.mybatisplus.extension.plugins.inner.TenantLineInnerInterceptor.processSelect(TenantLineInnerInterceptor.java:86)
	at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.processParser(JsqlParserSupport.java:91)
	at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.parserSingle(JsqlParserSupport.java:50)
	at com.baomidou.mybatisplus.extension.plugins.inner.TenantLineInnerInterceptor.beforeQuery(TenantLineInnerInterceptor.java:69)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:78)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at com.sun.proxy.$Proxy168.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:151)
	... 51 common frames omitted

```

**Comment by YunaiV** [comment]
已经修复。原因是，定时任务没有 tenant id，导致报错。
这块得在思考下，怎么做更合适一些。

**Comment by crimson-gao** [comment]
> 已经修复。原因是，定时任务没有 tenant id，导致报错。 这块得在思考下，怎么做更合适一些。

赞，谢谢！

**Comment by 1205747671** [comment]
@YunaiV master分支还是会报这个问题，`PayNotifyJob`任务

**Comment by kevinsir** [comment]
我也是这个问题，请问啥时候修复的？？
