### ISSUE TITLE
项目启动不了

### ISSUE THREAD

**Issue by fei1025** [YunaiV/ruoyi-vue-pro#717]
### 基本信息

- ruoyi-vue-pro 版本： JDK 8+ Spring Boot 2.7.18
- 操作系统： windows
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：可能是配置文件问题

### 复现步骤

第一步，
启动的时候报错
![9ace504909e15d1b1ab0a6389861781](https://github.com/user-attachments/assets/2c3ed6bd-1fc1-4268-bb25-2ba765967500)

第二步，
然后我把infa-api 这里的 <optional>true</optional> 去掉后可以启动
![image](https://github.com/user-attachments/assets/ea754881-770a-487a-9a43-19c2becb77af)

第三步,但是又报错
`Caused by: java.lang.IllegalStateException: Failed to introspect Class [com.mzt.logapi.starter.diff.DefaultDiffItemsToLogContentService] from ClassLoader [sun.misc.Launcher$AppClassLoader@18b4aac2]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:485)
	at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:321)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.buildLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:232)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.findLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:210)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(InitDestroyAnnotationBeanPostProcessor.java:149)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(CommonAnnotationBeanPostProcessor.java:305)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyMergedBeanDefinitionPostProcessors(AbstractAutowireCapableBeanFactory.java:1116)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	... 29 common frames omitted
Caused by: java.lang.NoClassDefFoundError: de/danielbechler/diff/node/DiffNode
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:467)
	... 36 common frames omitted
Caused by: java.lang.ClassNotFoundException: de.danielbechler.diff.node.DiffNode
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 40 common frames omitted
`

### 报错信息

带上必要的截图
![image](https://github.com/user-attachments/assets/23b12d29-a8b8-4241-ab80-16faa1791a25)

**Comment by YunaiV** [comment]
https://doc.iocoder.cn/quick-start/

参考文档。

ps：另外，有类不存在的报错，可以试试清空 idea 缓存。
