### ISSUE TITLE
Bug 每隔一段时间出现的 redis 空指针错误

### ISSUE THREAD

**Issue by crimson-gao** [YunaiV/ruoyi-vue-pro#74]
```text
2022-02-09 23:05:37.673 ERROR 5948 --- [SimpleAsyncTaskExecutor-1] [TID: N/A] ageListenerContainer$LoggingErrorHandler : Unexpected error occurred in scheduled task.

java.lang.NullPointerException: null
        at org.springframework.data.redis.stream.StreamPollTask.deserializeAndEmitRecords(StreamPollTask.java:171)
        at org.springframework.data.redis.stream.StreamPollTask.doLoop(StreamPollTask.java:148)
        at org.springframework.data.redis.stream.StreamPollTask.run(StreamPollTask.java:132)
        at java.lang.Thread.run(Unknown Source)
```
隔一段时间就触发，而且是 SimpleAsyncTaskExecutor-1 线程。看起来是定时任务触发的，redis stream 消息。

**Comment by crimson-gao** [comment]
但是并没有看出来有什么业务上的影响

**Comment by YunaiV** [comment]
redisson 的一个坑，我还在想有什么好办法解决~

**Comment by YunaiV** [comment]
已修复~

**Comment by five6** [comment]
![image](https://user-images.githubusercontent.com/21968901/168459451-9f6ac6cf-8026-4429-8daa-908aa35228e3.png)
大佬 1.62版本又出现这个问题了。
